name: Build CpHMD CUDA131 Container

on:
  push:
    branches: [ "main" ] # mainブランチに更新があったら実行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # イメージの名前を定義（ユーザー名/リポジトリ名:タグ名）
          tags: ghcr.io/${{ github.repository }}:latest
